apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: eso-auth
spec:
  provider:
    vault:
      server: https://vault-playground.edusuc.net
      path: Dev-secret        
      version: v2
      auth:
        userPass:
          path: userpass
          username: S11ahmed.wft
          secretRef:
            name: vault-auth
            namespace: external-secrets
            key: password
